esphome:
  name: ${device_name}

esp32:
  board: esp32dev
  framework:
    type: arduino

# Enable logging
logger:

# Enable Home Assistant API
api:
  password: ""
  reboot_timeout: 0s

ota:
  - platform: esphome
    password: ""

wifi:
  ssid: "moo-cow"
  password: "noshutup"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "${device_name} Fallback Hotspot"
    password: "UvJca6iPMmQC"

captive_portal:
    
i2c:
  # These are actually just the ESP32 defaults
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a

mqtt:
  broker: 192.168.1.203

sensor:
  - platform: bme280_i2c
    temperature:
      name: "temperature"
      id: "temperature"
      oversampling: 4x
      on_value:
        mqtt.publish_json:
          topic: "${device_name}/sensor/json"
          payload: |-
            root["temperature"] = id(temperature).state;
    pressure:
      name: "pressure"
      id: "pressure"
      on_value:
        mqtt.publish_json:
          topic: "${device_name}/sensor/json"
          payload: |-
            root["pressure"] = id(pressure).state;
    humidity:
      name: "humidity"
      id: "humidity"
      oversampling: 4x
      on_value:
        mqtt.publish_json:
          topic: "${device_name}/sensor/json"
          payload: |-
            root["humidity"] = id(humidity).state;
    address: 0x76
    update_interval: 60s
